### ISSUE TITLE
7.4: Locking Class

### ISSUE THREAD

**Issue by rafaelkallis** [alpox/CPP-Exercises#1]

**Comment by rafaelkallis** [comment]
@alpox 
@PascalSiemon 

Implementation finished, needs working RPN calculator.

**Comment by alpox** [comment]
@rafaelkallis @PascalSiemon Finished. Please take a look on the final version and give your ok if its good and you think all special cases are handled.

**Comment by rafaelkallis** [comment]
` g++ -c rpn.cpp -o rpn.o `
` rpn.cpp:78:68: error: expected expression `
 ` for_each(rpnStack.begin(), rpnStack.end(), [&] (T &entry) { cum = mymin(cum, entry); }); `

fixed with `-std=c++11` flag
